name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
    
    - name: 缓存 Buildozer 全局目录
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
    
    - name: 缓存 pip 包
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}
    
    - name: 安装 Python 依赖
      run: |
        pip install --upgrade pip
        pip install buildozer cython
    
    - name: 设置 Android SDK
      uses: android-actions/setup-android@v3
    
    - name: 接受 Android SDK 许可
      run: yes | sdkmanager --licenses
    
    - name: 构建 APK
      run: |
        buildozer android debug
    
    - name: 上传 APK
      uses: actions/upload-artifact@v4
      with:
        name: paddleocr-android-apk
        path: bin/*.apk
    
    - name: 获取版本信息
      id: version
      run: |
        VERSION=$(grep "version =" buildozer.spec | cut -d'=' -f2 | tr -d ' ')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: 创建 Release（如果是 tag）
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

